services:
  - type: web
    name: de
    env: deployment
    plan: free
    buildCommand: yarn --frozen-lockfile --prod=false && blitz build
    startCommand: blitz start -p ${PORT}
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET_KEY
        generateValue: true